version: '3.3'
services:
  BACKEND:
    image: 
    volumes:
      - ./app:/app
      - .m2:/root/.m2
    ports:
      - 8089:8089
    depends_on:
      - MYSQL-DATABASE
  MYSQL-DATABASE:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root

    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
 
